services:
  blog-app:
    container_name: blog-app
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
        NEXT_PUBLIC_AUTH_REDIRECT_TO: ${NEXT_PUBLIC_AUTH_REDIRECT_TO}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        OLLAMA_API_KEY: ${OLLAMA_API_KEY}
        OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
        OLLAMA_EMBED_API_KEY: ${OLLAMA_EMBED_API_KEY}
        OLLAMA_EMBED_BASE_URL: ${OLLAMA_EMBED_BASE_URL}
        OLLAMA_EMBED_MODEL: ${OLLAMA_EMBED_MODEL}
        OLLAMA_SMALL_MODEL: ${OLLAMA_SMALL_MODEL}
        OLLAMA_MEDIUM_MODEL: ${OLLAMA_MEDIUM_MODEL}
        VOYAGE_API_KEY: ${VOYAGE_API_KEY}
        LOGIN_PIN_NUMBER: ${LOGIN_PIN_NUMBER}
        NEXT_PUBLIC_VALID_EMAIL_CONFIRMED_AT: ${NEXT_PUBLIC_VALID_EMAIL_CONFIRMED_AT}
        VALID_USER_CREATED_AT: ${VALID_USER_CREATED_AT}
        METASEARCH_API_KEY: ${METASEARCH_API_KEY}

    restart: always

    ports:
      - 3031:3000

    networks:
      - npm-network

networks:
  npm-network:
    external: true
