import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/providers/auth-store-provider";
import { ToastProvider } from "@/providers/toast-provider";
import { AuthStoreProvider } from "@/providers/auth-provider";
import { LayoutStoreProvider } from "@/providers/layout-store-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body
        className={`antialiased h-screen flex flex-col bg-background text-foreground font-sans overflow-hidden `}
      >
        <ToastProvider />
        <AuthStoreProvider>
          <AuthProvider />
          <LayoutStoreProvider>{children}</LayoutStoreProvider>
        </AuthStoreProvider>
      </body>
    </html>
  );
}
