on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: appleboy/ssh-action@v1.2.0
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_AUTH_REDIRECT_TO: ${{ vars.NEXT_PUBLIC_AUTH_REDIRECT_TO }}
          NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LOGIN_PIN_NUMBER: ${{ secrets.LOGIN_PIN_NUMBER }}
          NEXT_PUBLIC_VALID_EMAIL_CONFIRMED_AT: ${{ vars.NEXT_PUBLIC_VALID_EMAIL_CONFIRMED_AT }}
          VALID_USER_CREATED_AT: ${{ secrets.VALID_USER_CREATED_AT }}
        with:
          envs: NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,SUPABASE_SERVICE_ROLE_KEY,NEXT_PUBLIC_AUTH_REDIRECT_TO,NEXT_PUBLIC_BASE_URL,OPENAI_API_KEY,LOGIN_PIN_NUMBER,NEXT_PUBLIC_VALID_EMAIL_CONFIRMED_AT,VALID_USER_CREATED_AT
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            trap 'echo "Deploy failed at line $LINENO"' ERR
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            REPO_DIR=~/${{ github.event.repository.name }}
            [ -d "$REPO_DIR/.git" ] || git clone --depth 1 https://github.com/${{ github.repository }}.git "$REPO_DIR"
            cd "$REPO_DIR"
            git fetch --prune --depth=1 origin main
            git reset --hard origin/main
            docker compose -f compose.prod.yaml build --pull
            docker compose -f compose.prod.yaml up -d --remove-orphans
